// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room_downsync_frame.proto

package treasurehunterx

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Direction struct {
	Dx                   float64  `protobuf:"fixed64,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy                   float64  `protobuf:"fixed64,2,opt,name=dy,proto3" json:"dy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Direction) Reset()         { *m = Direction{} }
func (m *Direction) String() string { return proto.CompactTextString(m) }
func (*Direction) ProtoMessage()    {}
func (*Direction) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{0}
}
func (m *Direction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Direction.Unmarshal(m, b)
}
func (m *Direction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Direction.Marshal(b, m, deterministic)
}
func (dst *Direction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Direction.Merge(dst, src)
}
func (m *Direction) XXX_Size() int {
	return xxx_messageInfo_Direction.Size(m)
}
func (m *Direction) XXX_DiscardUnknown() {
	xxx_messageInfo_Direction.DiscardUnknown(m)
}

var xxx_messageInfo_Direction proto.InternalMessageInfo

func (m *Direction) GetDx() float64 {
	if m != nil {
		return m.Dx
	}
	return 0
}

func (m *Direction) GetDy() float64 {
	if m != nil {
		return m.Dy
	}
	return 0
}

type Vec2D struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vec2D) Reset()         { *m = Vec2D{} }
func (m *Vec2D) String() string { return proto.CompactTextString(m) }
func (*Vec2D) ProtoMessage()    {}
func (*Vec2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{1}
}
func (m *Vec2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vec2D.Unmarshal(m, b)
}
func (m *Vec2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vec2D.Marshal(b, m, deterministic)
}
func (dst *Vec2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vec2D.Merge(dst, src)
}
func (m *Vec2D) XXX_Size() int {
	return xxx_messageInfo_Vec2D.Size(m)
}
func (m *Vec2D) XXX_DiscardUnknown() {
	xxx_messageInfo_Vec2D.DiscardUnknown(m)
}

var xxx_messageInfo_Vec2D proto.InternalMessageInfo

func (m *Vec2D) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vec2D) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Polygon2D struct {
	Anchor               *Vec2D   `protobuf:"bytes,1,opt,name=Anchor,proto3" json:"Anchor,omitempty"`
	Points               []*Vec2D `protobuf:"bytes,2,rep,name=Points,proto3" json:"Points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Polygon2D) Reset()         { *m = Polygon2D{} }
func (m *Polygon2D) String() string { return proto.CompactTextString(m) }
func (*Polygon2D) ProtoMessage()    {}
func (*Polygon2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{2}
}
func (m *Polygon2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon2D.Unmarshal(m, b)
}
func (m *Polygon2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon2D.Marshal(b, m, deterministic)
}
func (dst *Polygon2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon2D.Merge(dst, src)
}
func (m *Polygon2D) XXX_Size() int {
	return xxx_messageInfo_Polygon2D.Size(m)
}
func (m *Polygon2D) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon2D.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon2D proto.InternalMessageInfo

func (m *Polygon2D) GetAnchor() *Vec2D {
	if m != nil {
		return m.Anchor
	}
	return nil
}

func (m *Polygon2D) GetPoints() []*Vec2D {
	if m != nil {
		return m.Points
	}
	return nil
}

type Vec2DList struct {
	Vec2DList            []*Vec2D `protobuf:"bytes,1,rep,name=vec2DList,proto3" json:"vec2DList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vec2DList) Reset()         { *m = Vec2DList{} }
func (m *Vec2DList) String() string { return proto.CompactTextString(m) }
func (*Vec2DList) ProtoMessage()    {}
func (*Vec2DList) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{3}
}
func (m *Vec2DList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vec2DList.Unmarshal(m, b)
}
func (m *Vec2DList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vec2DList.Marshal(b, m, deterministic)
}
func (dst *Vec2DList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vec2DList.Merge(dst, src)
}
func (m *Vec2DList) XXX_Size() int {
	return xxx_messageInfo_Vec2DList.Size(m)
}
func (m *Vec2DList) XXX_DiscardUnknown() {
	xxx_messageInfo_Vec2DList.DiscardUnknown(m)
}

var xxx_messageInfo_Vec2DList proto.InternalMessageInfo

func (m *Vec2DList) GetVec2DList() []*Vec2D {
	if m != nil {
		return m.Vec2DList
	}
	return nil
}

type Polygon2DList struct {
	Polygon2DList        []*Polygon2D `protobuf:"bytes,1,rep,name=polygon2DList,proto3" json:"polygon2DList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Polygon2DList) Reset()         { *m = Polygon2DList{} }
func (m *Polygon2DList) String() string { return proto.CompactTextString(m) }
func (*Polygon2DList) ProtoMessage()    {}
func (*Polygon2DList) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{4}
}
func (m *Polygon2DList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon2DList.Unmarshal(m, b)
}
func (m *Polygon2DList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon2DList.Marshal(b, m, deterministic)
}
func (dst *Polygon2DList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon2DList.Merge(dst, src)
}
func (m *Polygon2DList) XXX_Size() int {
	return xxx_messageInfo_Polygon2DList.Size(m)
}
func (m *Polygon2DList) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon2DList.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon2DList proto.InternalMessageInfo

func (m *Polygon2DList) GetPolygon2DList() []*Polygon2D {
	if m != nil {
		return m.Polygon2DList
	}
	return nil
}

type BattleColliderInfo struct {
	StageName             string                    `protobuf:"bytes,1,opt,name=stageName,proto3" json:"stageName,omitempty"`
	StrToVec2DListMap     map[string]*Vec2DList     `protobuf:"bytes,2,rep,name=strToVec2DListMap,proto3" json:"strToVec2DListMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StrToPolygon2DListMap map[string]*Polygon2DList `protobuf:"bytes,3,rep,name=strToPolygon2DListMap,proto3" json:"strToPolygon2DListMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *BattleColliderInfo) Reset()         { *m = BattleColliderInfo{} }
func (m *BattleColliderInfo) String() string { return proto.CompactTextString(m) }
func (*BattleColliderInfo) ProtoMessage()    {}
func (*BattleColliderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{5}
}
func (m *BattleColliderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleColliderInfo.Unmarshal(m, b)
}
func (m *BattleColliderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleColliderInfo.Marshal(b, m, deterministic)
}
func (dst *BattleColliderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleColliderInfo.Merge(dst, src)
}
func (m *BattleColliderInfo) XXX_Size() int {
	return xxx_messageInfo_BattleColliderInfo.Size(m)
}
func (m *BattleColliderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleColliderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BattleColliderInfo proto.InternalMessageInfo

func (m *BattleColliderInfo) GetStageName() string {
	if m != nil {
		return m.StageName
	}
	return ""
}

func (m *BattleColliderInfo) GetStrToVec2DListMap() map[string]*Vec2DList {
	if m != nil {
		return m.StrToVec2DListMap
	}
	return nil
}

func (m *BattleColliderInfo) GetStrToPolygon2DListMap() map[string]*Polygon2DList {
	if m != nil {
		return m.StrToPolygon2DListMap
	}
	return nil
}

type Player struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    float64    `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64    `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Dir                  *Direction `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	Speed                int32      `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	BattleState          int32      `protobuf:"varint,6,opt,name=battleState,proto3" json:"battleState,omitempty"`
	LastMoveGmtMillis    int32      `protobuf:"varint,7,opt,name=lastMoveGmtMillis,proto3" json:"lastMoveGmtMillis,omitempty"`
	Score                int32      `protobuf:"varint,10,opt,name=score,proto3" json:"score,omitempty"`
	Removed              bool       `protobuf:"varint,11,opt,name=removed,proto3" json:"removed,omitempty"`
	JoinIndex            int32      `protobuf:"varint,12,opt,name=joinIndex,proto3" json:"joinIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{6}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetDir() *Direction {
	if m != nil {
		return m.Dir
	}
	return nil
}

func (m *Player) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Player) GetBattleState() int32 {
	if m != nil {
		return m.BattleState
	}
	return 0
}

func (m *Player) GetLastMoveGmtMillis() int32 {
	if m != nil {
		return m.LastMoveGmtMillis
	}
	return 0
}

func (m *Player) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Player) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *Player) GetJoinIndex() int32 {
	if m != nil {
		return m.JoinIndex
	}
	return 0
}

type PlayerMeta struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	JoinIndex            int32    `protobuf:"varint,5,opt,name=joinIndex,proto3" json:"joinIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMeta) Reset()         { *m = PlayerMeta{} }
func (m *PlayerMeta) String() string { return proto.CompactTextString(m) }
func (*PlayerMeta) ProtoMessage()    {}
func (*PlayerMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{7}
}
func (m *PlayerMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMeta.Unmarshal(m, b)
}
func (m *PlayerMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMeta.Marshal(b, m, deterministic)
}
func (dst *PlayerMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMeta.Merge(dst, src)
}
func (m *PlayerMeta) XXX_Size() int {
	return xxx_messageInfo_PlayerMeta.Size(m)
}
func (m *PlayerMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMeta proto.InternalMessageInfo

func (m *PlayerMeta) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerMeta) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *PlayerMeta) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *PlayerMeta) GetJoinIndex() int32 {
	if m != nil {
		return m.JoinIndex
	}
	return 0
}

type Treasure struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalIdInBattle      int32    `protobuf:"varint,2,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	X                    float64  `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,6,opt,name=removed,proto3" json:"removed,omitempty"`
	Type                 int32    `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Treasure) Reset()         { *m = Treasure{} }
func (m *Treasure) String() string { return proto.CompactTextString(m) }
func (*Treasure) ProtoMessage()    {}
func (*Treasure) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{8}
}
func (m *Treasure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Treasure.Unmarshal(m, b)
}
func (m *Treasure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Treasure.Marshal(b, m, deterministic)
}
func (dst *Treasure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Treasure.Merge(dst, src)
}
func (m *Treasure) XXX_Size() int {
	return xxx_messageInfo_Treasure.Size(m)
}
func (m *Treasure) XXX_DiscardUnknown() {
	xxx_messageInfo_Treasure.DiscardUnknown(m)
}

var xxx_messageInfo_Treasure proto.InternalMessageInfo

func (m *Treasure) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Treasure) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Treasure) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Treasure) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Treasure) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Treasure) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *Treasure) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Bullet struct {
	LocalIdInBattle      int32    `protobuf:"varint,1,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	LinearSpeed          float64  `protobuf:"fixed64,2,opt,name=linearSpeed,proto3" json:"linearSpeed,omitempty"`
	X                    float64  `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	StartAtPoint         *Vec2D   `protobuf:"bytes,6,opt,name=startAtPoint,proto3" json:"startAtPoint,omitempty"`
	EndAtPoint           *Vec2D   `protobuf:"bytes,7,opt,name=endAtPoint,proto3" json:"endAtPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bullet) Reset()         { *m = Bullet{} }
func (m *Bullet) String() string { return proto.CompactTextString(m) }
func (*Bullet) ProtoMessage()    {}
func (*Bullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{9}
}
func (m *Bullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bullet.Unmarshal(m, b)
}
func (m *Bullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bullet.Marshal(b, m, deterministic)
}
func (dst *Bullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bullet.Merge(dst, src)
}
func (m *Bullet) XXX_Size() int {
	return xxx_messageInfo_Bullet.Size(m)
}
func (m *Bullet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bullet.DiscardUnknown(m)
}

var xxx_messageInfo_Bullet proto.InternalMessageInfo

func (m *Bullet) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Bullet) GetLinearSpeed() float64 {
	if m != nil {
		return m.LinearSpeed
	}
	return 0
}

func (m *Bullet) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Bullet) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Bullet) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *Bullet) GetStartAtPoint() *Vec2D {
	if m != nil {
		return m.StartAtPoint
	}
	return nil
}

func (m *Bullet) GetEndAtPoint() *Vec2D {
	if m != nil {
		return m.EndAtPoint
	}
	return nil
}

type Trap struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalIdInBattle      int32    `protobuf:"varint,2,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	X                    float64  `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,6,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trap) Reset()         { *m = Trap{} }
func (m *Trap) String() string { return proto.CompactTextString(m) }
func (*Trap) ProtoMessage()    {}
func (*Trap) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{10}
}
func (m *Trap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trap.Unmarshal(m, b)
}
func (m *Trap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trap.Marshal(b, m, deterministic)
}
func (dst *Trap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trap.Merge(dst, src)
}
func (m *Trap) XXX_Size() int {
	return xxx_messageInfo_Trap.Size(m)
}
func (m *Trap) XXX_DiscardUnknown() {
	xxx_messageInfo_Trap.DiscardUnknown(m)
}

var xxx_messageInfo_Trap proto.InternalMessageInfo

func (m *Trap) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Trap) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Trap) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Trap) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Trap) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Trap) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type SpeedShoe struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalIdInBattle      int32    `protobuf:"varint,2,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	X                    float64  `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	Type                 int32    `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpeedShoe) Reset()         { *m = SpeedShoe{} }
func (m *SpeedShoe) String() string { return proto.CompactTextString(m) }
func (*SpeedShoe) ProtoMessage()    {}
func (*SpeedShoe) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{11}
}
func (m *SpeedShoe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeedShoe.Unmarshal(m, b)
}
func (m *SpeedShoe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeedShoe.Marshal(b, m, deterministic)
}
func (dst *SpeedShoe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeedShoe.Merge(dst, src)
}
func (m *SpeedShoe) XXX_Size() int {
	return xxx_messageInfo_SpeedShoe.Size(m)
}
func (m *SpeedShoe) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeedShoe.DiscardUnknown(m)
}

var xxx_messageInfo_SpeedShoe proto.InternalMessageInfo

func (m *SpeedShoe) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SpeedShoe) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *SpeedShoe) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SpeedShoe) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *SpeedShoe) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *SpeedShoe) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Pumpkin struct {
	LocalIdInBattle      int32    `protobuf:"varint,1,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	LinearSpeed          float64  `protobuf:"fixed64,2,opt,name=linearSpeed,proto3" json:"linearSpeed,omitempty"`
	X                    float64  `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pumpkin) Reset()         { *m = Pumpkin{} }
func (m *Pumpkin) String() string { return proto.CompactTextString(m) }
func (*Pumpkin) ProtoMessage()    {}
func (*Pumpkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{12}
}
func (m *Pumpkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pumpkin.Unmarshal(m, b)
}
func (m *Pumpkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pumpkin.Marshal(b, m, deterministic)
}
func (dst *Pumpkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pumpkin.Merge(dst, src)
}
func (m *Pumpkin) XXX_Size() int {
	return xxx_messageInfo_Pumpkin.Size(m)
}
func (m *Pumpkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pumpkin.DiscardUnknown(m)
}

var xxx_messageInfo_Pumpkin proto.InternalMessageInfo

func (m *Pumpkin) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Pumpkin) GetLinearSpeed() float64 {
	if m != nil {
		return m.LinearSpeed
	}
	return 0
}

func (m *Pumpkin) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Pumpkin) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Pumpkin) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type GuardTower struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalIdInBattle      int32    `protobuf:"varint,2,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	X                    float64  `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,6,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuardTower) Reset()         { *m = GuardTower{} }
func (m *GuardTower) String() string { return proto.CompactTextString(m) }
func (*GuardTower) ProtoMessage()    {}
func (*GuardTower) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{13}
}
func (m *GuardTower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuardTower.Unmarshal(m, b)
}
func (m *GuardTower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuardTower.Marshal(b, m, deterministic)
}
func (dst *GuardTower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuardTower.Merge(dst, src)
}
func (m *GuardTower) XXX_Size() int {
	return xxx_messageInfo_GuardTower.Size(m)
}
func (m *GuardTower) XXX_DiscardUnknown() {
	xxx_messageInfo_GuardTower.DiscardUnknown(m)
}

var xxx_messageInfo_GuardTower proto.InternalMessageInfo

func (m *GuardTower) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GuardTower) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *GuardTower) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GuardTower) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GuardTower) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *GuardTower) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type RoomDownsyncFrame struct {
	Id                   int32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RefFrameId           int32                 `protobuf:"varint,2,opt,name=refFrameId,proto3" json:"refFrameId,omitempty"`
	Players              map[int32]*Player     `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SentAt               int64                 `protobuf:"varint,4,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	CountdownNanos       int64                 `protobuf:"varint,5,opt,name=countdownNanos,proto3" json:"countdownNanos,omitempty"`
	Treasures            map[int32]*Treasure   `protobuf:"bytes,6,rep,name=treasures,proto3" json:"treasures,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Traps                map[int32]*Trap       `protobuf:"bytes,7,rep,name=traps,proto3" json:"traps,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Bullets              map[int32]*Bullet     `protobuf:"bytes,8,rep,name=bullets,proto3" json:"bullets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SpeedShoes           map[int32]*SpeedShoe  `protobuf:"bytes,9,rep,name=speedShoes,proto3" json:"speedShoes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Pumpkin              map[int32]*Pumpkin    `protobuf:"bytes,10,rep,name=pumpkin,proto3" json:"pumpkin,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	GuardTowers          map[int32]*GuardTower `protobuf:"bytes,11,rep,name=guardTowers,proto3" json:"guardTowers,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PlayerMetas          map[int32]*PlayerMeta `protobuf:"bytes,12,rep,name=playerMetas,proto3" json:"playerMetas,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoomDownsyncFrame) Reset()         { *m = RoomDownsyncFrame{} }
func (m *RoomDownsyncFrame) String() string { return proto.CompactTextString(m) }
func (*RoomDownsyncFrame) ProtoMessage()    {}
func (*RoomDownsyncFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_downsync_frame_e30cd20a583a4962, []int{14}
}
func (m *RoomDownsyncFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDownsyncFrame.Unmarshal(m, b)
}
func (m *RoomDownsyncFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDownsyncFrame.Marshal(b, m, deterministic)
}
func (dst *RoomDownsyncFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDownsyncFrame.Merge(dst, src)
}
func (m *RoomDownsyncFrame) XXX_Size() int {
	return xxx_messageInfo_RoomDownsyncFrame.Size(m)
}
func (m *RoomDownsyncFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDownsyncFrame.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDownsyncFrame proto.InternalMessageInfo

func (m *RoomDownsyncFrame) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomDownsyncFrame) GetRefFrameId() int32 {
	if m != nil {
		return m.RefFrameId
	}
	return 0
}

func (m *RoomDownsyncFrame) GetPlayers() map[int32]*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomDownsyncFrame) GetSentAt() int64 {
	if m != nil {
		return m.SentAt
	}
	return 0
}

func (m *RoomDownsyncFrame) GetCountdownNanos() int64 {
	if m != nil {
		return m.CountdownNanos
	}
	return 0
}

func (m *RoomDownsyncFrame) GetTreasures() map[int32]*Treasure {
	if m != nil {
		return m.Treasures
	}
	return nil
}

func (m *RoomDownsyncFrame) GetTraps() map[int32]*Trap {
	if m != nil {
		return m.Traps
	}
	return nil
}

func (m *RoomDownsyncFrame) GetBullets() map[int32]*Bullet {
	if m != nil {
		return m.Bullets
	}
	return nil
}

func (m *RoomDownsyncFrame) GetSpeedShoes() map[int32]*SpeedShoe {
	if m != nil {
		return m.SpeedShoes
	}
	return nil
}

func (m *RoomDownsyncFrame) GetPumpkin() map[int32]*Pumpkin {
	if m != nil {
		return m.Pumpkin
	}
	return nil
}

func (m *RoomDownsyncFrame) GetGuardTowers() map[int32]*GuardTower {
	if m != nil {
		return m.GuardTowers
	}
	return nil
}

func (m *RoomDownsyncFrame) GetPlayerMetas() map[int32]*PlayerMeta {
	if m != nil {
		return m.PlayerMetas
	}
	return nil
}

func init() {
	proto.RegisterType((*Direction)(nil), "treasurehunterx.Direction")
	proto.RegisterType((*Vec2D)(nil), "treasurehunterx.Vec2D")
	proto.RegisterType((*Polygon2D)(nil), "treasurehunterx.Polygon2D")
	proto.RegisterType((*Vec2DList)(nil), "treasurehunterx.Vec2DList")
	proto.RegisterType((*Polygon2DList)(nil), "treasurehunterx.Polygon2DList")
	proto.RegisterType((*BattleColliderInfo)(nil), "treasurehunterx.BattleColliderInfo")
	proto.RegisterMapType((map[string]*Polygon2DList)(nil), "treasurehunterx.BattleColliderInfo.StrToPolygon2DListMapEntry")
	proto.RegisterMapType((map[string]*Vec2DList)(nil), "treasurehunterx.BattleColliderInfo.StrToVec2DListMapEntry")
	proto.RegisterType((*Player)(nil), "treasurehunterx.Player")
	proto.RegisterType((*PlayerMeta)(nil), "treasurehunterx.PlayerMeta")
	proto.RegisterType((*Treasure)(nil), "treasurehunterx.Treasure")
	proto.RegisterType((*Bullet)(nil), "treasurehunterx.Bullet")
	proto.RegisterType((*Trap)(nil), "treasurehunterx.Trap")
	proto.RegisterType((*SpeedShoe)(nil), "treasurehunterx.SpeedShoe")
	proto.RegisterType((*Pumpkin)(nil), "treasurehunterx.Pumpkin")
	proto.RegisterType((*GuardTower)(nil), "treasurehunterx.GuardTower")
	proto.RegisterType((*RoomDownsyncFrame)(nil), "treasurehunterx.RoomDownsyncFrame")
	proto.RegisterMapType((map[int32]*Bullet)(nil), "treasurehunterx.RoomDownsyncFrame.BulletsEntry")
	proto.RegisterMapType((map[int32]*GuardTower)(nil), "treasurehunterx.RoomDownsyncFrame.GuardTowersEntry")
	proto.RegisterMapType((map[int32]*PlayerMeta)(nil), "treasurehunterx.RoomDownsyncFrame.PlayerMetasEntry")
	proto.RegisterMapType((map[int32]*Player)(nil), "treasurehunterx.RoomDownsyncFrame.PlayersEntry")
	proto.RegisterMapType((map[int32]*Pumpkin)(nil), "treasurehunterx.RoomDownsyncFrame.PumpkinEntry")
	proto.RegisterMapType((map[int32]*SpeedShoe)(nil), "treasurehunterx.RoomDownsyncFrame.SpeedShoesEntry")
	proto.RegisterMapType((map[int32]*Trap)(nil), "treasurehunterx.RoomDownsyncFrame.TrapsEntry")
	proto.RegisterMapType((map[int32]*Treasure)(nil), "treasurehunterx.RoomDownsyncFrame.TreasuresEntry")
}

func init() {
	proto.RegisterFile("room_downsync_frame.proto", fileDescriptor_room_downsync_frame_e30cd20a583a4962)
}

var fileDescriptor_room_downsync_frame_e30cd20a583a4962 = []byte{
	// 1091 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x97, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x80, 0xb5, 0x5e, 0xaf, 0x93, 0x3d, 0x76, 0x93, 0x66, 0x44, 0xc3, 0x36, 0xa0, 0xca, 0x5a,
	0x24, 0x14, 0xa9, 0xad, 0x4b, 0xd3, 0x0a, 0xa1, 0x5c, 0x20, 0xd2, 0x06, 0x2a, 0x4b, 0xa4, 0x0d,
	0x6b, 0x03, 0x42, 0x5c, 0x94, 0x89, 0x77, 0x12, 0x2f, 0x59, 0xef, 0xac, 0x66, 0xc6, 0xae, 0xf7,
	0x0d, 0x10, 0x5c, 0xc0, 0x15, 0x4f, 0xc0, 0x5b, 0xf0, 0x2e, 0x3c, 0x0a, 0x42, 0x3b, 0x3b, 0xeb,
	0x9d, 0xfd, 0x49, 0xb0, 0xd2, 0x8b, 0xde, 0x79, 0xce, 0x9e, 0xf3, 0x9d, 0x33, 0xe7, 0x67, 0x66,
	0x0c, 0x77, 0x19, 0xa5, 0xb3, 0xd7, 0x3e, 0x7d, 0x13, 0xf1, 0x24, 0x9a, 0xbc, 0x3e, 0x67, 0x78,
	0x46, 0x06, 0x31, 0xa3, 0x82, 0xa2, 0x6d, 0xc1, 0x08, 0xe6, 0x73, 0x46, 0xa6, 0xf3, 0x48, 0x10,
	0xb6, 0x74, 0xef, 0x83, 0x7d, 0x1c, 0x30, 0x32, 0x11, 0x01, 0x8d, 0xd0, 0x16, 0xb4, 0xfc, 0xa5,
	0x63, 0xf4, 0x8d, 0x7d, 0xc3, 0x6b, 0xf9, 0x4b, 0xb9, 0x4e, 0x9c, 0x96, 0x5a, 0x27, 0xee, 0x47,
	0x60, 0x7d, 0x47, 0x26, 0x07, 0xc7, 0xa8, 0x07, 0x46, 0xae, 0x67, 0x2c, 0xd3, 0x55, 0xae, 0x65,
	0x24, 0xee, 0x25, 0xd8, 0xa7, 0x34, 0x4c, 0x2e, 0x68, 0x74, 0x70, 0x8c, 0x06, 0xd0, 0x39, 0x8a,
	0x26, 0x53, 0xca, 0xa4, 0x76, 0xf7, 0x60, 0x77, 0x50, 0x09, 0x60, 0x20, 0x81, 0x9e, 0xd2, 0x4a,
	0xf5, 0x4f, 0x69, 0x10, 0x09, 0xee, 0xb4, 0xfa, 0xe6, 0x75, 0xfa, 0x99, 0x96, 0x7b, 0x04, 0xb6,
	0x14, 0x7c, 0x1d, 0x70, 0x81, 0x9e, 0x82, 0xbd, 0xc8, 0x17, 0x8e, 0x71, 0xad, 0x7d, 0xa1, 0xe8,
	0x7e, 0x03, 0xb7, 0x56, 0xf1, 0x4a, 0xcc, 0x17, 0x70, 0x2b, 0xd6, 0x05, 0x0a, 0xb5, 0x57, 0x43,
	0xad, 0xcc, 0xbc, 0xb2, 0x81, 0xfb, 0x8f, 0x09, 0xe8, 0x19, 0x16, 0x22, 0x24, 0xcf, 0x69, 0x18,
	0x06, 0x3e, 0x61, 0xc3, 0xe8, 0x9c, 0xa2, 0x0f, 0xc1, 0xe6, 0x02, 0x5f, 0x90, 0x97, 0x78, 0x46,
	0x64, 0x3e, 0x6c, 0xaf, 0x10, 0xa0, 0x29, 0xec, 0x70, 0xc1, 0xc6, 0x74, 0xb5, 0x9f, 0x13, 0x1c,
	0xab, 0x2c, 0x1c, 0xd6, 0x5c, 0xd7, 0xe9, 0x83, 0x51, 0xd5, 0xf8, 0xcb, 0x48, 0xb0, 0xc4, 0xab,
	0x43, 0x91, 0x80, 0x3b, 0x52, 0x58, 0xda, 0x76, 0xea, 0xcd, 0x94, 0xde, 0x3e, 0x5f, 0xdb, 0x5b,
	0x15, 0x90, 0x79, 0x6c, 0x86, 0xef, 0xfd, 0x04, 0xbb, 0xcd, 0x21, 0xa2, 0xdb, 0x60, 0x5e, 0x92,
	0x44, 0x65, 0x24, 0xfd, 0x89, 0x3e, 0x01, 0x6b, 0x81, 0xc3, 0x39, 0x91, 0x5d, 0xd5, 0x94, 0xfa,
	0x15, 0xc4, 0xcb, 0x14, 0x0f, 0x5b, 0x9f, 0x19, 0x7b, 0x53, 0xd8, 0xbb, 0x3a, 0xac, 0x06, 0x2f,
	0x4f, 0xcb, 0x5e, 0xee, 0x5d, 0x5d, 0xe0, 0x8a, 0x27, 0xf7, 0xcf, 0x16, 0x74, 0x4e, 0x43, 0x9c,
	0x10, 0x96, 0xce, 0x48, 0xe0, 0x4b, 0xaa, 0xe5, 0xb5, 0x02, 0x3f, 0x1b, 0x8d, 0x56, 0x69, 0x34,
	0x4c, 0x35, 0x1a, 0xe8, 0x01, 0x98, 0x7e, 0xc0, 0x9c, 0xf6, 0x15, 0x9b, 0x5a, 0x0d, 0xa2, 0x97,
	0xaa, 0xa1, 0xf7, 0xc0, 0xe2, 0x31, 0x21, 0xbe, 0x63, 0x49, 0x78, 0xb6, 0x40, 0x7d, 0xe8, 0x9e,
	0xc9, 0x72, 0x8c, 0x04, 0x16, 0xc4, 0xe9, 0xc8, 0x6f, 0xba, 0x08, 0x3d, 0x80, 0x9d, 0x10, 0x73,
	0x71, 0x42, 0x17, 0xe4, 0xc5, 0x4c, 0x9c, 0x04, 0x61, 0x18, 0x70, 0x67, 0x43, 0xea, 0xd5, 0x3f,
	0x48, 0x2f, 0x13, 0xca, 0x88, 0x03, 0xca, 0x4b, 0xba, 0x40, 0x0e, 0x6c, 0x30, 0x32, 0xa3, 0x0b,
	0xe2, 0x3b, 0xdd, 0xbe, 0xb1, 0xbf, 0xe9, 0xe5, 0xcb, 0xb4, 0x89, 0x7f, 0xa6, 0x41, 0x34, 0x8c,
	0x7c, 0xb2, 0x74, 0x7a, 0xd2, 0xa6, 0x10, 0xb8, 0xbf, 0x18, 0x00, 0x59, 0x62, 0x4e, 0x88, 0xc0,
	0xb5, 0xe4, 0x20, 0x68, 0x47, 0x69, 0xf3, 0xb7, 0x64, 0x11, 0xe4, 0xef, 0x74, 0x43, 0x7e, 0xc0,
	0xe3, 0x10, 0x27, 0x72, 0x2e, 0x4c, 0xf9, 0x49, 0x17, 0xa1, 0x5d, 0xe8, 0xe0, 0x05, 0x16, 0x38,
	0xcb, 0x9c, 0xed, 0xa9, 0x55, 0x39, 0x14, 0xab, 0x1a, 0xca, 0x5f, 0x06, 0x6c, 0x8e, 0x55, 0x86,
	0x6b, 0x81, 0xec, 0xc3, 0x76, 0x48, 0x27, 0x38, 0x1c, 0xfa, 0xc3, 0x28, 0xeb, 0x6e, 0x19, 0x93,
	0xe5, 0x55, 0xc5, 0x45, 0x7e, 0x4c, 0x3d, 0x3f, 0xb2, 0xca, 0xed, 0x52, 0x95, 0xad, 0xbc, 0xca,
	0x5a, 0xee, 0x3a, 0xe5, 0xdc, 0x21, 0x68, 0x8b, 0x24, 0x26, 0xaa, 0x18, 0xf2, 0xb7, 0xfb, 0xaf,
	0x01, 0x9d, 0x67, 0xf3, 0x30, 0x24, 0xa2, 0x29, 0x28, 0xa3, 0x39, 0xa8, 0x3e, 0x74, 0xc3, 0x20,
	0x22, 0x98, 0x8d, 0x64, 0x83, 0x64, 0xed, 0xa6, 0x8b, 0xb2, 0x00, 0xcd, 0x52, 0x80, 0xed, 0x86,
	0x00, 0xad, 0x72, 0x80, 0x87, 0xd0, 0xe3, 0x02, 0x33, 0x71, 0x24, 0xe4, 0xf9, 0x2a, 0xe3, 0xbf,
	0xfa, 0x10, 0x2d, 0xe9, 0xa2, 0x4f, 0x01, 0x48, 0xe4, 0xe7, 0x96, 0x1b, 0xd7, 0x5a, 0x6a, 0x9a,
	0xee, 0xaf, 0x06, 0xb4, 0xc7, 0x0c, 0xc7, 0x6f, 0x51, 0xa3, 0x3c, 0xaf, 0x66, 0x91, 0xd7, 0x9b,
	0x55, 0xc8, 0xfd, 0xdd, 0x00, 0x5b, 0x26, 0x70, 0x34, 0xa5, 0x6f, 0xd3, 0x35, 0x37, 0x4b, 0x7f,
	0xbe, 0x8f, 0x8e, 0xd6, 0x1f, 0xbf, 0x19, 0xb0, 0x71, 0x3a, 0x9f, 0xc5, 0x97, 0x41, 0xf4, 0xee,
	0x1b, 0xc4, 0xfd, 0xc3, 0x00, 0x78, 0x31, 0xc7, 0xcc, 0x1f, 0xd3, 0x37, 0x0d, 0x87, 0xdf, 0xbb,
	0x28, 0xd9, 0xdf, 0x5d, 0xd8, 0xf1, 0x28, 0x9d, 0x1d, 0xab, 0xf7, 0xce, 0x57, 0xe9, 0x73, 0xa7,
	0x16, 0xd9, 0x3d, 0x00, 0x46, 0xce, 0xe5, 0xb7, 0xa1, 0xaf, 0x82, 0xd2, 0x24, 0x68, 0x08, 0x1b,
	0xb1, 0x3c, 0xb7, 0xb8, 0xba, 0x05, 0x1f, 0xd5, 0x5a, 0xb7, 0xe6, 0x64, 0x90, 0x9d, 0x74, 0x3c,
	0xbb, 0xf6, 0x72, 0xfb, 0xf4, 0xb8, 0xe2, 0x24, 0x12, 0x47, 0x42, 0xee, 0xc5, 0xf4, 0xd4, 0x0a,
	0x7d, 0x0c, 0x5b, 0x13, 0x3a, 0x8f, 0x44, 0xfa, 0x30, 0x7b, 0x89, 0x23, 0xca, 0xe5, 0xee, 0x4c,
	0xaf, 0x22, 0x45, 0xaf, 0xc0, 0xce, 0x5d, 0x73, 0xa7, 0x23, 0x83, 0x79, 0xbc, 0x46, 0x30, 0xf9,
	0x59, 0xa7, 0xc2, 0x29, 0x18, 0xe8, 0x39, 0x58, 0x82, 0xe1, 0x38, 0xbd, 0x04, 0x52, 0xd8, 0xc3,
	0xb5, 0x60, 0x38, 0x56, 0xa0, 0xcc, 0x36, 0x4d, 0xd0, 0x99, 0x3c, 0xa6, 0xb8, 0xb3, 0xb9, 0x76,
	0x82, 0xb2, 0x83, 0x2d, 0x4f, 0x90, 0xb2, 0x47, 0x1e, 0x00, 0xcf, 0x67, 0x8c, 0x3b, 0xb6, 0xa4,
	0x1d, 0xac, 0x41, 0x5b, 0x0d, 0xa6, 0x02, 0x6a, 0x14, 0x59, 0xbf, 0x6c, 0x4a, 0x1c, 0x58, 0xbf,
	0x7e, 0x99, 0x45, 0x5e, 0x3f, 0x35, 0x65, 0xdf, 0x42, 0xf7, 0x62, 0xd5, 0xe2, 0xdc, 0xe9, 0x4a,
	0xdc, 0x93, 0x35, 0x70, 0xc5, 0x60, 0xa8, 0x00, 0x75, 0x4e, 0x8a, 0x8d, 0x57, 0x37, 0x23, 0x77,
	0x7a, 0x6b, 0x63, 0x8b, 0xfb, 0x34, 0xc7, 0x6a, 0x9c, 0xbd, 0x11, 0xf4, 0xf4, 0x36, 0xd4, 0x9f,
	0x39, 0x56, 0xf6, 0xcc, 0x79, 0x58, 0x7e, 0xe6, 0xbc, 0x5f, 0x7f, 0xe6, 0x48, 0x7b, 0xfd, 0x25,
	0xf5, 0x3d, 0x6c, 0x95, 0xdb, 0xa9, 0x01, 0xfb, 0xa8, 0x8c, 0xbd, 0x5b, 0xc3, 0xe6, 0x04, 0x1d,
	0xfc, 0x0a, 0xa0, 0x68, 0xad, 0x06, 0xe8, 0xfd, 0x32, 0xf4, 0x4e, 0x03, 0x14, 0xc7, 0x3a, 0x70,
	0x04, 0x3d, 0xbd, 0xc9, 0x6e, 0xb2, 0xfd, 0xcc, 0x5e, 0x87, 0xfe, 0x00, 0xdb, 0x95, 0x5e, 0x6b,
	0xe0, 0xfe, 0xef, 0x1b, 0x75, 0x85, 0xd0, 0xd1, 0x63, 0xe8, 0xe9, 0x5d, 0xd7, 0xc0, 0x1d, 0x94,
	0xb9, 0x4e, 0xbd, 0x5c, 0x99, 0xbd, 0x4e, 0xfd, 0x11, 0x6e, 0x57, 0x9b, 0xaf, 0x81, 0xfc, 0xb8,
	0x4c, 0xfe, 0xa0, 0x46, 0x2e, 0x18, 0x15, 0x78, 0xb5, 0x05, 0x6f, 0x02, 0x2f, 0x18, 0x1a, 0xfc,
	0xac, 0x23, 0xff, 0x97, 0x3e, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x08, 0x30, 0x86, 0xf5, 0xb4,
	0x0e, 0x00, 0x00,
}
